# Generated by Django 6.0.4 on 2026-04-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprendimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('emprendimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprendimientos.emprendimiento')),
            ],
        ),
    ]
